name: Primary

on:
  pull_request:
  push:
  release:

jobs:
  report:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: echo stuff
        run: |
          echo "Primary is executing"
