name: Primary

on:
  pull_request:
  push:
  release:
    types: [published] # each web release causes: created, published, released

jobs:
  report:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: echo stuff
        run: |
          echo "Primary is executing."
          echo "My trigger was:"
          echo "    ${{ github.event_name }}"
          echo "My ref was:"
          echo "    ${{ github.ref }}"
          echo "My sha was:"
          echo "    ${{ github.sha }}"
      - name: Failure
        run: |
          exit 1
      - name: Don't Care Success Test
        run: |
          echo "This runs always?"
      - name: Success Test
        if: success()
        run: |
          echo "This runs on success."
      - name: Release Trigger
        if: success() && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: pypi-release
          client-payload: '{"sha": "${{ github.sha }}", "ref": "${{ github.ref }}", "message": "    hello from primary!"}'
