name: Primary

on:
  pull_request:
  push:
  release:

jobs:
  report:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: echo stuff
        run: |
          echo "Primary is executing"
      - name: Repository Dispatch
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: peter-evans/repository-dispatch@v1.1.3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          event-type: primary-invoke
          client-payload: '{"message": "    hello from primary!"}'
