name: Secondary

on:
  repository_dispatch:
    types: [pypi-release]

jobs:
  report:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: Check out from "${{ github.event.client_payload.ref}}"
        uses: actions/checkout@v2
        with:
          ref:  ${{ github.event.client_payload.sha}}
      - name: echo stuff
        run: |
          echo "Secondary is executing"
          echo "Message from Primary:"
          echo "${{ github.event.client_payload.message }}"
          echo "Primary ref:"
          echo "${{ github.event.client_payload.ref}}"
          echo "Primary sha:"
          echo "${{ github.event.client_payload.sha}}"
