name: Secondary

on:
  repository_dispatch:
    types: [primary-invoke]

jobs:
  report:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
      - name: echo stuff
        run: |
          echo "Secondary is executing"
          echo "Message from Primary:"
          echo "${{ github.event.client_payload.message }}"
